ITMO Султанов Мирзомансурхон Махсудович ДЗ-1
Ultimatereo/kotlin-itmo-2022 pull request #1
Opened 2022-12-22 11:40 UTC by Ultimatereo

2023-01-05 18:27 UTC, FireF0xIl requested changes
Когда была оригинальная дата коммита?

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/Shape.kt
> +
Это неэффективно, т.к. вычисление `reduce` происходит каждый раз, а в нашем случае `size` никак не может измениться.

-0.5

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +}
Хотелось бы сообщение об ошибке, дать пользователю понять что вообще произошло.

-0.5

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
В задании явно сказано реализовать view через отдельную реализацию интерфейса.

-1

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +            if (point.dim(i) < 0 || point.dim(i) >= shape.dim(i)) {
Лучше писать неравенства в одном направлении: `point.dim(i) < 0 || shape.dim(i) <= point.dim(i)`

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
Нужно было создать и вернуть именно копии а не изначальные объекты.

-0.25

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
Почему бы прямо тут не бросить исключение?

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/Point.kt
> +    }
Детали реализации должны быть приватными функциями (можно перенести в `DefaultNDArray`) как расширение, используя `dim`

-0.25

2023-01-05 18:27 UTC, FireF0xIl commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +        }
Какой тогда был смысл хранить данные в мапе, а потом при вычислении всё равно конвертировать это в обычные списки? Кажется, что использование мапов для такой довольно низкоуровневой библиотеки (как упомянутый в задании `numpy`), где важна скорость исполнения и занимаемая память, неоправданно. + по пути для записи в мапу создаётся куча промежуточных объектов, аллокация которых явно не бесплатна. К тому же я довольно-таки уверен, что в реальной жизни матрицы будут заполнены более менее разными значениями (спустя несколько операций с матрицами) и в итоге на каждую точку будет создан целый объект вместо потенциальной реализации, где используется только 1 массив, где каждое число будет занимать только  размер инта и для проведения операций нужно только аккуратно подсчитывать индексы. Хотелось бы получить комментарий.

-1

2023-01-26 23:30 UTC, Ultimatereo commented
> Когда была оригинальная дата коммита?

16 декабря

2023-01-26 23:31 UTC, Ultimatereo commented on homework01/src/main/kotlin/Shape.kt
> +
fixed

2023-01-26 23:31 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +}
fixed

2023-01-26 23:35 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
fixed

2023-01-26 23:35 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +            if (point.dim(i) < 0 || point.dim(i) >= shape.dim(i)) {
fixed

2023-01-26 23:36 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
fixed

2023-01-26 23:36 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +    }
fixed

2023-01-26 23:36 UTC, Ultimatereo commented on homework01/src/main/kotlin/Point.kt
> +    }
fixed

2023-01-26 23:44 UTC, Ultimatereo commented on homework01/src/main/kotlin/DefaultNDArray.kt
> +        }
В целом, согласен со всем сказанным. Когда начинал делать задание, думал про ndarray с огромным количеством элементов, где большинство элементов это дефолтные значения. В таком случае операции set и at действительно будут работать быстрее, однако чем больше мы заполняем массив, тем медленнее это решение становится по сравнению с решением с обычным массивом.

2023-12-27 11:53 UTC, merged