ITMO Султанов Мирзомансурхон Махсудович ДЗ-2
Ultimatereo/kotlin-itmo-2022 pull request #2
Opened 2022-12-22 11:40 UTC by Ultimatereo

2023-01-12 19:04 UTC, Shashulovskiy requested changes

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +import com.google.common.collect.Iterators
Зачем?

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> map(f: (T) -> U): FList<U> {
Функция падает со StackOverflow при большом размере листа (например 100000)

-3 за все

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun filter(f: (T) -> Boolean): FList<T> {
Функция падает со StackOverflow при большом размере листа (например 100000)

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> fold(base: U, f: (U, T) -> U): U {
Функция падает со StackOverflow при большом размере листа (например 100000)

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +fun <T> flistOf(vararg values : T) : FList<T> {
Функция падает со StackOverflow при большом размере листа (например 100000)

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +    private fun plusImpl(first: FList<BinomialTree<T>>, second: FList<BinomialTree<T>>) : FList<BinomialTree<T>> =
Говорят, эта функция не испльзуется

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +    private fun plusImpl1(first:FList<BinomialTree<T>>, second: FList<BinomialTree<T>>,
Давай уберем цифры из наименований функций

-0.5

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +        if (first.isEmpty) {
Тут происходит какая-то страшная копипаста

-0.5

2023-01-12 19:04 UTC, Shashulovskiy commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +        if (heap.tail is FList.Cons && heap.head.order == heap.tail.head.order) {
Тут происходит какая-то страшная копипаста

2023-01-27 01:35 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +import com.google.common.collect.Iterators
fixed

2023-01-27 01:35 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> map(f: (T) -> U): FList<U> {
fixed

2023-01-27 01:35 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun filter(f: (T) -> Boolean): FList<T> {
fixed

2023-01-27 01:35 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +        override fun <U> fold(base: U, f: (U, T) -> U): U {
fixed

2023-01-27 01:35 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/FList.kt
> +fun <T> flistOf(vararg values : T) : FList<T> {
fixed

2023-01-27 01:36 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +    private fun plusImpl(first: FList<BinomialTree<T>>, second: FList<BinomialTree<T>>) : FList<BinomialTree<T>> =
fixed

2023-01-27 01:36 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +    private fun plusImpl1(first:FList<BinomialTree<T>>, second: FList<BinomialTree<T>>,
fixed

2023-01-27 01:39 UTC, Ultimatereo commented on homework02/lib/src/main/kotlin/binomial/BinomialHeap.kt
> +        if (first.isEmpty) {
Копипасты на самом деле там дальше нет, по-моему. Там разные случаи рассматриваются, и они все различны.

2023-12-27 11:54 UTC, closed without merging